CONFIG_MBEDTLS_RIPEMD160_C=n
# 【修复】原预设禁用 SHA1，但 WPA2 4-way 握手必需 HMAC-SHA1，改为启用
CONFIG_MBEDTLS_SHA1_C=y
CONFIG_MBEDTLS_CAMELLIA_C=n
CONFIG_MBEDTLS_SELF_TEST=n
CONFIG_MBEDTLS_HARDWARE_SHA=y
CONFIG_MBEDTLS_HARDWARE_MPI=y
CONFIG_MBEDTLS_HARDWARE_AES=y
